#! /bin/bash
set -eux

docker build -t tapstream/openresty-bundle-deb .
CONTAINER=$(docker create tapstream/openresty-bundle-deb)
if [ ! -d ./artifacts ]; then
    mkdir ./artifacts
fi
docker cp $CONTAINER:/build/openresty_1.9.3.1-tapstream1_amd64.deb ./artifacts/
docker rm $CONTAINER
